version: "3"

services:
  web:
    build:
      context: '.'
    command: "yarn serve:prod"
    expose:
      - "4200"
    ports:
#      - "4200:4200"
      - "9876:3333"
    restart: unless-stopped
#    volumes:
    environment:
      - VIRTUAL_HOST=dnd-audio.lessi.ng
      - VIRTUAL_PORT=4200
      - VIRTUAL_NETWORK=webnet
#      - LETSENCRYPT_HOST=images.putit.at
#      - LETSENCRYPT_EMAIL=lessing.paul@gmail.com
    networks:
      webnet:

networks:
  webnet:
    external: true
